# title: 综合题库文档中心
theme: minima
# description: 题库查询系统
plugins:
     - jekyll-search
     - jekyll-seo-tag
# defaults:
#   - scope:
#       path: ""
#     values:
#       layout: default
collections:
  ground_flare:
    output: true
    permalink: /ground-flare/:path/
  water_pump:
    output: true
    permalink: /water-pump/:path/

